export const authType = {
  CUSTOMER_LOGIN_START: "CUSTOMER_LOGIN_START",
  CUSTOMER_LOGIN_SUCCESS: "CUSTOM_LOGIN_SUCCESS",
  CUSTOMER_LOGIN_FAILURE: "CUSTOMER_LOGIN_FAILURE",

  CUSTOMER_LOGOUT: "CUSTOMER_LOGOUT",

  GET_CUSTOMER_PROFILE_START: "GET_CUSTOMER_PROFILE_START",
  GET_CUSTOMER_PROFILE_SUCCESS: "GET_CUSTOMER_PROFILE_SUCCESS",
  GET_CUSTOMER_PROFILE_FAILURE: "GET_CUSTOMER_PROFILE_FAILURE",

  GET_PROFILE_BY_TOKEN: "GET_PROFILE_BY_TOKEN",
};
