export const LAY_THONG_TIN_LICH_CHIEU_PHIM = 'LAY_THONG_TIN_LICH_CHIEU_PHIM';
export const GET_ARRAY_HE_THONG_RAP = 'GET_ARRAY_HE_THONG_RAP';
export const LAY_THONG_TIN_LICH_CHIEU_HE_THONG_RAP = 'LAY_THONG_TIN_LICH_CHIEU_HE_THONG_RAP';